export const rugFactoryAbi = [
  {
    type: "function",
    name: "createRug",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "params",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "metadataURI", type: "string" },
          { name: "metadataHash", type: "bytes32" },
          { name: "creatorStake", type: "uint256" },
        ],
      },
    ],
    outputs: [{ name: "rug", type: "address" }],
  },
  {
    type: "function",
    name: "WBNB",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "creationFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "minCreatorStake",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "createPaused",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "tokenTotalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "founderBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "swapFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "protocolFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "minLaunchBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "openingCapBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "openingDuration",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint40" }],
  },
  {
    type: "function",
    name: "founderUnlockDelay",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint40" }],
  },
  {
    type: "event",
    name: "RugCreated",
    inputs: [
      { indexed: true, name: "rug", type: "address" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "name", type: "string" },
      { indexed: false, name: "symbol", type: "string" },
      { indexed: false, name: "creatorStake", type: "uint256" },
      { indexed: false, name: "openingEnd", type: "uint40" },
      { indexed: false, name: "metadataHash", type: "bytes32" },
      { indexed: false, name: "disclosureHash", type: "bytes32" },
    ],
  },
] as const;

export const rugInstanceAbi = [
  {
    type: "event",
    name: "Contributed",
    inputs: [
      { indexed: true, name: "rug", type: "address" },
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "LaunchFailed",
    inputs: [
      { indexed: true, name: "rug", type: "address" },
      { indexed: false, name: "totalContributed", type: "uint256" },
      { indexed: false, name: "minLaunchAmount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "LaunchSucceeded",
    inputs: [
      { indexed: true, name: "rug", type: "address" },
      { indexed: true, name: "token", type: "address" },
      { indexed: true, name: "pool", type: "address" },
      { indexed: false, name: "totalContributed", type: "uint256" },
      { indexed: false, name: "acceptedContribution", type: "uint256" },
      { indexed: false, name: "openingTokenAllocation", type: "uint256" },
      { indexed: false, name: "poolTokenReserve", type: "uint256" },
      { indexed: false, name: "poolQuoteReserve", type: "uint256" },
      { indexed: false, name: "founderAllocation", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "ClaimedOpening",
    inputs: [
      { indexed: true, name: "rug", type: "address" },
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "tokenAmount", type: "uint256" },
      { indexed: false, name: "refundAmount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "ClaimedFailedRefund",
    inputs: [
      { indexed: true, name: "rug", type: "address" },
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "CreatorStakeWithdrawn",
    inputs: [
      { indexed: true, name: "rug", type: "address" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "RugPulled",
    inputs: [
      { indexed: true, name: "rug", type: "address" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "founderTokensSold", type: "uint256" },
      { indexed: false, name: "quoteOut", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "contribute",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  { type: "function", name: "finalize", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "claimOpening", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "claimFailedRefund", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "withdrawCreatorStakeAfterFailure",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "rug",
    stateMutability: "nonpayable",
    inputs: [
      { name: "minQuoteOut", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ name: "quoteOut", type: "uint256" }],
  },
  { type: "function", name: "status", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "factory", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "creator", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "token", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "pool", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "creatorStake", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "minLaunchAmount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "openingCap", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "openingStart", stateMutability: "view", inputs: [], outputs: [{ type: "uint40" }] },
  { type: "function", name: "openingEnd", stateMutability: "view", inputs: [], outputs: [{ type: "uint40" }] },
  { type: "function", name: "founderUnlockTime", stateMutability: "view", inputs: [], outputs: [{ type: "uint40" }] },
  { type: "function", name: "swapFeeBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint16" }] },
  { type: "function", name: "protocolFeeBps", stateMutability: "view", inputs: [], outputs: [{ type: "uint16" }] },
  { type: "function", name: "metadataURI", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "totalContributed", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "acceptedContribution", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "openingTokenAllocation", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "poolTokenReserve", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "poolQuoteReserve", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "founderRemaining", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "contributionOf",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "claimed",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "bool" }],
  },
] as const;

export const rugPoolAbi = [
  {
    type: "event",
    name: "Swap",
    inputs: [
      { indexed: true, name: "pool", type: "address" },
      { indexed: true, name: "sender", type: "address" },
      { indexed: true, name: "to", type: "address" },
      { indexed: false, name: "isBuy", type: "bool" },
      { indexed: false, name: "amountIn", type: "uint256" },
      { indexed: false, name: "amountOut", type: "uint256" },
      { indexed: false, name: "protocolFeeQuote", type: "uint256" },
      { indexed: false, name: "reserveToken", type: "uint112" },
      { indexed: false, name: "reserveQuote", type: "uint112" },
    ],
  },
  {
    type: "function",
    name: "buyExactQuoteForTokens",
    stateMutability: "nonpayable",
    inputs: [
      { name: "quoteIn", type: "uint256" },
      { name: "minTokensOut", type: "uint256" },
      { name: "to", type: "address" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ name: "tokensOut", type: "uint256" }],
  },
  {
    type: "function",
    name: "sellExactTokensForQuote",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenIn", type: "uint256" },
      { name: "minQuoteOut", type: "uint256" },
      { name: "to", type: "address" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ name: "quoteOut", type: "uint256" }],
  },
  {
    type: "function",
    name: "getReserves",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "reserveToken", type: "uint112" },
      { name: "reserveQuote", type: "uint112" },
    ],
  },
  {
    type: "function",
    name: "protocolFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
  {
    type: "function",
    name: "swapFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint16" }],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
] as const;

export const wbnbAbi = [
  ...erc20Abi,
  { type: "function", name: "deposit", stateMutability: "payable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "wad", type: "uint256" }],
    outputs: [],
  },
] as const;
